services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: lararel_image
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - ipp_vp
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - ipp_vp
    database:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_ipp_dk
            MYSQL_USER: laravel
            MYSQL_PASSWORD: passer
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - ipp_vp

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - database
        networks:
            - ipp_vp



networks:
    ipp_vp:

volumes:
    db_data:

